name: Build and Deploy

on:
   push:
      branches:
         - main

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: echo "Building and Deploying"
           run: echo "Building and Deploying"

         - name: Checkout code
           uses: actions/checkout@v3

         

