name: Build and Deploy

on:
   push:
      branches:
         - main

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Deploy via rsync over SSH
           uses: burnett01/rsync-deployments@v8
           with:
               switches: -avzr --delete --exclude=".git" --exclude=".well-known"
               path: ./
               remote_path: /var/www/html/
               remote_host: ${{ secrets.SSH_HOST }}
               remote_port: ${{ secrets.SSH_PORT }}
               remote_user: ${{ secrets.SSH_USERNAME }}
               remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

         - name: Build application with tsc
           uses: appleboy/ssh-action@v1.0.3
           with:
               host: ${{ secrets.SSH_HOST }}
               port: ${{ secrets.SSH_PORT }}
               username: ${{ secrets.SSH_USERNAME }}
               key: ${{ secrets.SSH_PRIVATE_KEY }}
               script: |
                  npx tsc -p tsconfig.json

